api_platform:
    enable_fos_user: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    graphql:
        graphiql:
            enabled: true
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header